### PR TITLE
preserve alignment for indicator

### PR DESCRIPTION
**Pull request by zkat**
Before:
screen shot 2019-03-04 at 09 44 19

After:
screen shot 2019-03-04 at 09 44 11

### CODE REVIEW

**Comment by zkat** [comment]
Not really sure what these `textContent` errors are all about 🤔

**Comment by vadimdemedes** [comment]
Hm, interesting, will check it out.

**Comment by vadimdemedes** [comment]
Fixed in Ink 2.0.3 :)

**Comment by vadimdemedes** [comment]
Going to merge it and then fix a few other things myself, thank you!

**Comment by vadimdemedes** [comment]
Released as 3.0.1 ;)

**Pull request merged**
