### PR TITLE
Add `limit` prop

### LINKED ISSUE #2: Add paging functionality
If you have a huge list with items, you might want to limit how many that is showing, like in https://github.com/sindresorhus/fkill-cli.

I could do a PR if you want.

### PR DESCRIPTION
**Pull request by kevva**
Not super happy with having to rotate the items on every render, but since we want "endless scroll" functionality I couldn't find another way.

Fixes #2.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
CI is failing. Thanks for this PR though!

**Comment by kevva** [comment]
Yeah, were som linting errors in `master`. Should work now though.

**Comment by vadimdemedes** [comment]
Thanks @kevva!

**Comment by vadimdemedes** [comment]
Published as `1.1.0`.

**Pull request merged**
